# Please consult conda-forge/core before doing this
c_stdlib_version:          # [osx and x86_64]
  - "10.14"                # [osx and x86_64]
c_stdlib_version:          # [osx and x86_64]
  - "10.14"                # [osx and x86_64]
