{% set version = "0.4.11" %}

# try to avoid bot mangling
{% if 1 %}
# avoid selectors in output `script` for _other_ bot
{% set build_script = "build-oxigraph.sh" %}
{% set build_script = "bld-oxigraph.bat" %}   # [win]
{% endif %}

package:
  name: oxigraph-split
  version: {{ version }}

source:
  url: https://github.com/oxigraph/oxigraph/releases/download/v{{ version }}/oxigraph_v{{ version }}.tar.gz
  sha256: ca5767e74e92f3df533abbd1eb80ae418b725605cb74edd82875dc277ddb8ffc

build:
  number: 3

requirements:
  build:
    - libclang                            # [win]
    - llvm                                # [win]
    - llvm-tools                          # [win]
    - clangdev                            # [not osx]
    - llvmdev                             # [not osx]
    - pkg-config                          # [not (win or build_platform != target_platform)]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - python                              # [build_platform != target_platform]
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ compiler("rust") }}
    - {{ stdlib("c") }}
    - cargo-bundle-licenses
    - maturin >=1.0,<2.0
  host:
    - rocksdb                             # [not (win or build_platform != target_platform)]
    - zstd                                # [not (win or build_platform != target_platform)]
    - pip
    - python
    - maturin >=1.0,<2.0
  run:
    - ca-certificates
    - python
    - rocksdb                             # [not (win or build_platform != target_platform)]
    - zstd                                # [not (win or build_platform != target_platform)]

outputs:
  - name: oxigraph-server
    script: {{ build_script }}
    build:
      # build `oxigraph-server` once
      skip: true  # [py != 312]
      ignore_run_exports:
        - python
        - python_abi
    requirements:
      build:
        - libclang                  # [win]
        - llvm                      # [win]
        - llvm-tools                # [win]
        - clangdev                  # [not osx]
        - llvmdev                   # [not osx]
        - pkg-config                # [not (win or build_platform != target_platform)]
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - {{ compiler("rust") }}
        - {{ stdlib("c") }}
        - cargo-bundle-licenses
      host:
        - rocksdb                   # [not (win or build_platform != target_platform)]
        - openssl                   # [unix]
        - zstd                      # [not (win or build_platform != target_platform)]
      run:
        - ca-certificates
        - openssl                   # [unix]
        - rocksdb                   # [not (win or build_platform != target_platform)]
        - zstd                      # [not (win or build_platform != target_platform)]
    test:
      commands:
        - oxigraph --version
        - oxigraph --help
    about:
      home: https://oxigraph.org
      summary: a SPARQL database and RDF toolkit
      license: Apache-2.0 OR MIT
      license_file:
        - LICENSE-APACHE
        - LICENSE-MIT
        - cli/THIRDPARTY.yml
      dev_url: https://github.com/oxigraph/oxigraph

  - name: pyoxigraph
    script: {{ build_script }}
    requirements:
      build:
        - libclang                            # [win]
        - llvm                                # [win]
        - llvm-tools                          # [win]
        - clangdev                            # [not osx]
        - llvmdev                             # [not osx]
        - pkg-config                          # [not (win or build_platform != target_platform)]
        - cross-python_{{ target_platform }}  # [build_platform != target_platform]
        - python                              # [build_platform != target_platform]
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - {{ compiler("rust") }}
        - {{ stdlib("c") }}
        - cargo-bundle-licenses
        - maturin >=1.0,<2.0
      host:
        - rocksdb                             # [not (win or build_platform != target_platform)]
        - zstd                                # [not (win or build_platform != target_platform)]
        - pip
        - python
        - maturin >=1.0,<2.0
      run:
        - ca-certificates
        - python
        - rocksdb                             # [not (win or build_platform != target_platform)]
        - zstd                                # [not (win or build_platform != target_platform)]
    test:
      files:
        - test_licenses.py
      source_files:
        - python/tests
      imports:
        - pyoxigraph
      commands:
        - pip check
        - cd python/tests
        - pytest -vv --color=yes --tb=long
        - mypy -p pyoxigraph
      requires:
        - mypy
        - pip
        - pytest
    about:
      home: https://oxigraph.org
      summary: Python bindings of Oxigraph, a SPARQL database and RDF toolkit
      license: Apache-2.0 OR MIT
      license_file:
        - LICENSE-APACHE
        - LICENSE-MIT
        - python/THIRDPARTY.yml
      dev_url: https://github.com/oxigraph/oxigraph/tree/main/python
      doc_url: https://pyoxigraph.readthedocs.io


about:
  home: https://oxigraph.org
  summary: a SPARQL database and RDF toolkit
  license: Apache-2.0 OR MIT
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
  dev_url: https://github.com/oxigraph/oxigraph
  doc_url: https://oxigraph.org

extra:
  feedstock-name: oxigraph
  recipe-maintainers:
    - Tpt
    - bollwyvl
