{% set version = "0.3.7" %}
{% set build_number = 0 %}

package:
  name: oxigraph
  version: {{ version }}

source:
  url: https://github.com/oxigraph/oxigraph/releases/download/v{{ version }}/oxigraph_v{{ version }}.tar.gz
  sha256: fbdd9c9f4060c4efb0c2345aee65c54c4594abfd0bd1cfceb15a6fac03aa8d14

build:
  number: {{ build_number }}

outputs:
  - name: oxigraph-server
    build:
      number: {{ build_number }}
      script:
        - bash {{ RECIPE_DIR }}/build-oxigraph.sh  # [unix]
        - call {{ RECIPE_DIR }}\bld-oxigraph-server.bat  # [win]
    requirements:
      build:
        - {{ compiler('rust') }}
        - {{ compiler('c') }}                    # [unix]
        - {{ compiler('cxx') }}                  # [unix]
        - {{ compiler('m2w64_c') }}              # [win]
        - {{ compiler('m2w64_cxx') }}            # [win]
        - cargo-bundle-licenses
      host:
        - clangdev                               # [not osx]
        - llvmdev                                # [not osx]
        - openssl
    test:
      commands:
        - oxigraph_server --version
        - oxigraph_server --help

  - name: pyoxigraph
    build:
      number: {{ build_number }}
      script:
        - bash {{ RECIPE_DIR }}/build-oxigraph.sh  # [unix]
        - call {{ RECIPE_DIR }}\bld-pyoxigraph.bat  # [win]
    requirements:
      build:
        - {{ compiler('rust') }}
        - {{ compiler('c') }}                    # [unix]
        - {{ compiler('cxx') }}                  # [unix]
        - {{ compiler('m2w64_c') }}              # [win]
        - {{ compiler('m2w64_cxx') }}            # [win]
        - maturin >=0.11,<0.12
        - cargo-bundle-licenses
      host:
        - clangdev                               # [not osx]
        - llvmdev                                # [not osx]
        - openssl
        - python
        - pip
      run:
        - python
    test:
      files:
        - test_licenses.py
      source_files:
        - python/tests
      imports:
        - pyoxigraph
      commands:
        - pip check
        - cd python/tests
        - pytest -vv --cov pyoxigraph --cov-report term-missing:skip-covered --cov-fail-under 100
      requires:
        - pip
        - pytest-cov
        - ruamel_yaml
        # fails pip check: https://github.com/conda-forge/importlib_metadata-feedstock/issues/88
        - importlib-metadata !=4.7.1

about:
  home: https://oxigraph.org
  summary: a SPARQL database and RDF toolkit
  license: Apache-2.0 OR MIT
  license_file:
    # first-party
    - LICENSE-APACHE
    - LICENSE-MIT
    - THIRDPARTY.yml

  dev_url: https://github.com/oxigraph/oxigraph
  doc_url: https://oxigraph.org

extra:
  feedstock-name: oxigraph
  recipe-maintainers:
    - bollwyvl
