{% set min_rust = "rust >=1.60" %}
{% set version = "0.3.14" %}
{% set build_number = 0 %}
{% set min_rust = "rust >=1.60" %}

package:
  name: oxigraph
  version: {{ version }}

source:
  url: https://github.com/oxigraph/oxigraph/releases/download/v{{ version }}/oxigraph_v{{ version }}.tar.gz
  sha256: d0bcff61bd3aaa046568657652c6871208359e925d1d2c5eb1fd42af2543519b

build:
  number: {{ build_number }}

outputs:
  - name: oxigraph-server
    build:
      number: {{ build_number }}
      script:
        - bash {{ RECIPE_DIR }}/build-oxigraph.sh  # [unix]
        - call {{ RECIPE_DIR }}\bld-oxigraph-server.bat  # [win]
    requirements:
      build:
        - {{ compiler('c') }}                    # [unix]
        - {{ compiler('cxx') }}                  # [unix]
        - {{ compiler('m2w64_c') }}              # [win]
        - {{ compiler('m2w64_cxx') }}            # [win]
        - m2w64-binutils                         # [win]
        - {{ min_rust }}
        - cargo-bundle-licenses
        - clangdev                               # [not osx]
        - llvmdev                                # [not osx]
      run:
        - ca-certificates
    test:
      commands:
        - oxigraph_server --version
        - oxigraph_server --help

  - name: pyoxigraph
    build:
      number: {{ build_number }}
      script:
        - bash {{ RECIPE_DIR }}/build-oxigraph.sh  # [unix]
        - call {{ RECIPE_DIR }}\bld-pyoxigraph.bat  # [win]
    requirements:
      build:
        - {{ compiler('c') }}                    # [unix]
        - {{ compiler('cxx') }}                  # [unix]
        - {{ compiler('m2w64_c') }}              # [win]
        - {{ compiler('m2w64_cxx') }}            # [win]
        - m2w64-binutils                         # [win]
        - {{ min_rust }}
        - maturin >=0.14.0,<0.15.0
        - cargo-bundle-licenses
        - clangdev                               # [not osx]
        - llvmdev                                # [not osx]
      host:
        - pip
        - python
      run:
        - python
        - ca-certificates
    test:
      files:
        - test_licenses.py
      source_files:
        - python/tests
      imports:
        - pyoxigraph
      commands:
        - pip check
        - cd python/tests
        - pytest -vv --cov pyoxigraph --cov-report term-missing:skip-covered --cov-fail-under 100
        - mypy -m pyoxigraph  # [py>=39]
      requires:
        - mypy
        - pip
        - pytest-cov
        - ruamel_yaml
        # fails pip check: https://github.com/conda-forge/importlib_metadata-feedstock/issues/88
        - importlib-metadata !=4.7.1

about:
  home: https://oxigraph.org
  summary: a SPARQL database and RDF toolkit
  license: Apache-2.0 OR MIT
  license_file:
    # first-party
    - LICENSE-APACHE
    - LICENSE-MIT
    - THIRDPARTY.yml

  dev_url: https://github.com/oxigraph/oxigraph
  doc_url: https://oxigraph.org

extra:
  feedstock-name: oxigraph
  recipe-maintainers:
    - Tpt
    - bollwyvl
