# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.5.11"
  build_number: 1
  cargo_wrapper: cargo-auditable-wrapper.${{ "bat" if win else "sh" }}
  maturin_min: "1.0"
  maturin_max: "2.0"
  python_check_max: "3.14"

recipe:
  name: oxigraph-split
  version: ${{ version | replace("-post.", ".post") }}

source:
  url: https://github.com/oxigraph/oxigraph/releases/download/v${{ version }}/oxigraph_v${{ version }}.tar.gz
  sha256: 563c7ad6dc397cdbedb8ab9a1f4fdc671d9d5119b43d9498d8e4d0bc0b6a2567

build:
  number: ${{ build_number }}

outputs:
  - package:
      name: oxigraph-server
    build:
      skip: not is_python_min
      script:
        file: build-oxigraph
    requirements:
      build:
        - ${{ compiler("c") }}
        - ${{ compiler("cxx") }}
        - ${{ compiler("rust") }}
        - ${{ stdlib("c") }}
        - cargo-bundle-licenses
        - cargo-auditable
        - if: win
          then:
            - libclang
            - llvm
            - llvm-tools
        - if: not osx
          then:
            - clangdev
            - llvmdev
        - if: unix
          then:
            - pkg-config
      host:
        - if: unix
          then:
            - rocksdb
            - openssl
            - zstd
      run:
        - ca-certificates
        - if: unix
          then:
            - openssl
            - rocksdb
            - zstd
    tests:
      - script:
          - oxigraph --version
          - oxigraph --help
    about:
      summary: a SPARQL database and RDF toolkit
      license: Apache-2.0 OR MIT
      license_file:
        - LICENSE-APACHE
        - LICENSE-MIT
        - cli/THIRDPARTY.yml
      homepage: https://oxigraph.org
      repository: https://github.com/oxigraph/oxigraph

  - package:
      name: pyoxigraph
    build:
      skip: is_abi3 and not is_python_min
      python:
        version_independent: ${{ is_abi3 }}
      script:
        file: build-oxigraph
    requirements:
      build:
        - ${{ compiler("c") }}
        - ${{ compiler("cxx") }}
        - ${{ compiler("rust") }}
        - ${{ stdlib("c") }}
        - cargo-auditable
        - cargo-bundle-licenses
        - if: win
          then:
            - libclang
            - llvm
            - llvm-tools
        - if: not osx
          then:
            - clangdev
            - llvmdev
        - if: unix
          then:
            - pkg-config
      host:
        - pip
        - python
        - maturin >=${{ maturin_min }},<${{ maturin_max }}
        - if: unix
          then:
            - rocksdb
            - zstd
        - if: is_abi3
          then:
            - python-abi3
            - python ${{ python_min }}.*
      run:
        - ca-certificates
        - python
        - if: unix
          then:
            - rocksdb
            - zstd
        - if: is_abi3
          then:
            - python-abi3
            - python >=${{ python_min }}
    tests:
      - package_contents:
          strict: true
          files:
            - etc/conda/test-files/pyoxigraph/**
          site_packages:
            - pyoxigraph/**
            - pyoxigraph-${{ version }}.dist-info/**
      - python:
          imports: pyoxigraph
          pip_check: true
          python_version:
            - if: is_abi3
              then:
                - ${{ python_min }}.*
                - ${{ python_check_max }}.*
              else:
                - "*"
      - files:
          recipe:
            - test_licenses.py
          source:
            - python/tests/**
        requirements:
          run:
            - pytest
            - if: target_platform != "win-arm64"
              then:
                - mypy
            - if: is_abi3
              then:
                - abi3audit
                - python ${{ python_min }}.*
        script:
          - cd python/tests
          - pytest -vv --color=yes --tb=long
          - if: target_platform != "win-arm64"
            then:
              - mypy -p pyoxigraph
          - if: is_abi3
            then:
              - if: unix
                then: abi3audit -s -v --assume-minimum-abi3 ${{ python_min }} "${SP_DIR}/pyoxigraph/pyoxigraph.abi3.so"
                else: abi3audit -s -v --assume-minimum-abi3 ${{ python_min }} "%SP_DIR\pyoxigraph\pyoxigraph.pyd"
    about:
      summary: Python bindings of Oxigraph, a SPARQL database and RDF toolkit
      license: Apache-2.0 OR MIT
      license_file:
        - LICENSE-APACHE
        - LICENSE-MIT
        - python/THIRDPARTY.yml
      homepage: https://pypi.org/project/pyoxigraph
      repository: https://github.com/oxigraph/oxigraph/tree/main/python
      documentation: https://pyoxigraph.readthedocs.io

about:
  summary: a SPARQL database and RDF toolkit
  license: Apache-2.0 OR MIT
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
  homepage: https://oxigraph.org
  repository: https://github.com/oxigraph/oxigraph
  documentation: https://oxigraph.org

extra:
  feedstock-name: oxigraph
  recipe-maintainers:
    - Tpt
    - bollwyvl
