# try to avoid bot mangling
# avoid selectors in output `script` for _other_ bot
schema_version: 1

context:
  version: "0.5.6"
  build_number: 0
  maturin_min: "1.0"
  maturin_max: "2.0"
  python_check_max: "3.14"
  # abi3 audit
  abi3_ext: ${{ "pyd" if win else "abi3.so" }}
  unix_sp_dir: |-
    $(python -c "print(__import__('site').getsitepackages()[-1])")/pyoxigraph
  win_sp_dir: |-
    Lib\site-packages\pyoxigraph
  sp_dir: |-
    ${{ "%PREFIX%\\" ~ win_sp_dir if win else unix_sp_dir }}

recipe:
  name: oxigraph-split
  version: ${{ version | replace("-post.", ".post") }}

source:
  url: https://github.com/oxigraph/oxigraph/releases/download/v${{ version }}/oxigraph_v${{ version }}.tar.gz
  sha256: 8dfdab7fefa5ebb5cbd5d5887c98efae09c6d7b3cf068d618720de0ca546675f

build:
  number: ${{ build_number }}

outputs:
  - package:
      name: oxigraph-server
    build:
      skip: not is_python_min
      script:
        file: build-oxigraph
    requirements:
      build:
        - ${{ compiler("c") }}
        - ${{ compiler("cxx") }}
        - ${{ compiler("rust") }}
        - ${{ stdlib("c") }}
        - cargo-bundle-licenses
        - cargo-auditable
        - if: win
          then:
            - libclang
            - llvm
            - llvm-tools
        - if: not osx
          then:
            - clangdev
            - llvmdev
        - if: not (win or build_platform != target_platform)
          then:
            - pkg-config
      host:
        - if: not (win or build_platform != target_platform)
          then:
            - rocksdb
            - openssl
            - zstd
      run:
        - ca-certificates
        - if: unix
          then:
            - openssl
        - if: not (win or build_platform != target_platform)
          then:
            - rocksdb
            - zstd
    tests:
      - script:
          - oxigraph --version
          - oxigraph --help
    about:
      summary: a SPARQL database and RDF toolkit
      license: Apache-2.0 OR MIT
      license_file:
        - LICENSE-APACHE
        - LICENSE-MIT
        - cli/THIRDPARTY.yml
      homepage: https://oxigraph.org
      repository: https://github.com/oxigraph/oxigraph

  - package:
      name: pyoxigraph
    build:
      skip: is_abi3 and not is_python_min
      python:
        version_independent: ${{ is_abi3 }}
      script:
        file: build-oxigraph
    requirements:
      build:
        - ${{ compiler("c") }}
        - ${{ compiler("cxx") }}
        - ${{ compiler("rust") }}
        - ${{ stdlib("c") }}
        - cargo-bundle-licenses
        - if: win
          then:
            - libclang
            - llvm
            - llvm-tools
        - if: not osx
          then:
            - clangdev
            - llvmdev
        - if: not (win or build_platform != target_platform)
          then:
            - pkg-config
        - if: build_platform != target_platform
          then:
            - cross-python_${{ target_platform }}
            - python
            - maturin >=${{ maturin_min }},<${{ maturin_max }}
      host:
        - pip
        - python
        - maturin >=${{ maturin_min }},<${{ maturin_max }}
        - if: not (win or build_platform != target_platform)
          then:
            - rocksdb
            - zstd
        - if: is_abi3
          then:
            - python-abi3
      run:
        - ca-certificates
        - python
        - if: not (win or build_platform != target_platform)
          then:
            - rocksdb
            - zstd
      ignore_run_exports:
        from_package:
          - cross-python_${{ target_platform }}
    tests:
      - if: is_abi3
        then:
          - python:
              imports: pyoxigraph
              pip_check: true
              python_version:
                - ${{ python_min }}.*
                - ${{ python_check_max }}.*
          - requirements
          - script
        else:
          - python:
              imports: pyoxigraph
              pip_check: true
      - files:
          recipe:
            - test_licenses.py
          source:
            - python/tests/
        requirements:
          run:
            - mypy
            - pytest
            - if: is_abi3
              then:
                - python ${{ python_min }}.*
        script:
          - cd python/tests
          - pytest -vv --color=yes --tb=long
          - mypy -p pyoxigraph
    about:
      summary: Python bindings of Oxigraph, a SPARQL database and RDF toolkit
      license: Apache-2.0 OR MIT
      license_file:
        - LICENSE-APACHE
        - LICENSE-MIT
        - python/THIRDPARTY.yml
      homepage: https://pypi.org/project/pyoxigraph
      repository: https://github.com/oxigraph/oxigraph/tree/main/python
      documentation: https://pyoxigraph.readthedocs.io

about:
  summary: a SPARQL database and RDF toolkit
  license: Apache-2.0 OR MIT
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
  homepage: https://oxigraph.org
  repository: https://github.com/oxigraph/oxigraph
  documentation: https://oxigraph.org

extra:
  feedstock-name: oxigraph
  recipe-maintainers:
    - Tpt
    - bollwyvl
