azure:
  settings_win:
    variables:
      CONDA_BLD_PATH: C:\\bld\\
  store_build_artifacts: true
build_platform:
  osx_arm64: osx_64
conda_build:
  pkg_format: '2'
conda_forge_output_validation: true
conda_install_tool: pixi
github:
  branch_name: main
  tooling_branch_name: main
test: native_and_emulated
