azure:
  store_build_artifacts: true
  settings_win:
    variables:
      # https://github.com/conda-forge/oxigraph-feedstock/pull/74
      ## slow, but runs out of space during cargo build
      CONDA_BLD_PATH: C:\\bld\\
build_platform:
  osx_arm64: osx_64
conda_build:
  pkg_format: '2'
conda_forge_output_validation: true
conda_install_tool: pixi
github:
  branch_name: main
  tooling_branch_name: main
test: native_and_emulated
